### ISSUE TITLE
include axios to the library dependencies ?

### ISSUE THREAD

**Issue by JerryGreen** [schettino/react-request-hook#9]
two reasons:

1. to lock axios version which is properly working with `react-request-hook`
2. to get rid of this unnecessary setting:

<RequestProvider **_value={axios}_**>

**Comment by petergledhill** [comment]
I think this very useful to be able to pass in an axios instance.  For example our instance makes use of middleware to add headers to requests.  We couldn't do this if this was sealed.

**Comment by JerryGreen** [comment]
@petergledhill first of all, it makes sense to add `axios` to library dependencies anyway

But I got your thought - axios may still be able to be passed (only if needed), for example

**Comment by schettino** [comment]
The main ideas behind adding it as a peer rather than a dependency directly are: 
 1) be less restrictive with the current `axios`' version an user might have (besides the cancellable feature, we're pretty much just passing down the request config object to axios).
 2) to avoid adding multiple axios versions on the user's bundle.
 3) we could give the option to use Fetch in the future (with the same API).

As it's more likely to have use cases where we configure/create an Axios instance beforehand, I'd leave as-is to avoid breaking changes in the future. But it all depends on the path we take from now on.

**Comment by JerryGreen** [comment]
> we could give the option to use Fetch in the future (with the same API)

This sounds very cool, I would want to use Fetch API rather than axios

Though, this is hard - they just have different APIs, and it's probably better to ship some v2 with similar but different API (why to support axios, in first place?)

So my concern actually narrows to just this - it's just a bit confusing to see such an example in readme:

```
import {RequestProvider} from 'react-request-hook';
import axios from 'axios';

ReactDOM.render(
  <RequestProvider value={axios}>
    <App />
  </RequestProvider>,
  document.getElementById('root'),
);
```

Because axios seems redundant here (which is not), especially if you are not familiar with axios

I think I may close the issue but you may take a look here, maybe it's a good idea to change readme to make it less confusing: https://github.com/schettino/react-request-hook/pull/10
